spring.application.name=usuario

#Puerto de la aplicación
server.port=0

# Configuración de la conexión (MySQL Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/elbuensabor_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Recomendado para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect